version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore(deps)'

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    patterns:
      - '*'
    multi-ecosystem-group: 'dependencies'
    versioning-strategy: 'auto'

  - package-ecosystem: 'github-actions'
    directory: '/'
    patterns:
      - '*'
    multi-ecosystem-group: 'dependencies'
